### ISSUE TITLE
The Moonlit Path: Fenrir is mean

### ISSUE THREAD

**Issue by AvNytemare** [Lynnea1320/topaz#11]
Fenrir Prime should be using Howling Moon around 50% for the first time, in 3 runs he has used it at 66%, 85%, and 93% instantly wiping a group of 5 with Shell V on and the moon phase being 21%, 3~ party members are level 80. The fight also auto kicks you immediately after a wipe even when Reraise is used.

**Comment by Lynnea1320** [comment]
A workaround has been implemented that should ease the difficulty for now until the mob move system is overhauled with more customizability.
